services:
  app-backend:
    container_name: app-backend
    image: lynaten/app-backend:latest
    build: ./backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      TZ: ${TZ}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}

  app-web:
    container_name: app-web
    image: lynaten/app-web:latest
    build:
      context: ./web
      args:
        NEXT_PUBLIC_BACKEND_HTTP: ${NEXT_PUBLIC_BACKEND_HTTP}
        NEXT_PUBLIC_BACKEND_WS: ${NEXT_PUBLIC_BACKEND_WS}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      TZ: ${TZ}
      PORT: ${WEB_PORT}
      SITE_URL: ${SITE_URL}
      BACKEND_URL: ${BACKEND_URL}
      NEXT_PUBLIC_BACKEND_HTTP: ${NEXT_PUBLIC_BACKEND_HTTP}
      NEXT_PUBLIC_BACKEND_WS: ${NEXT_PUBLIC_BACKEND_WS}
