services:
  app-backend:
    container_name: app-backend
    image: app-backend:1.0.0
    build: ./backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      TZ: ${TZ}
  app-web:
    container_name: app-web
    image: app-web:1.0.0
    build:
      context: ./web
      args:
        NEXT_PUBLIC_BACKEND_HTTP: http://localhost:${BACKEND_PORT}
        NEXT_PUBLIC_BACKEND_WS: ws://localhost:${BACKEND_PORT}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      TZ: ${TZ}
      PORT: ${WEB_PORT}
      BACKEND_URL: http://app-backend:${BACKEND_PORT}
      NEXT_PUBLIC_BACKEND_HTTP: http://localhost:${BACKEND_PORT}
      NEXT_PUBLIC_BACKEND_WS: ws://localhost:${BACKEND_PORT}
      SITE_URL: http://localhost:${WEB_PORT}
